### ISSUE TITLE
Check Discord

### ISSUE THREAD

**Issue by Reginald-Gillespie** [Dddatt/Karlson-3D#3]
I don't trust KA not to hide my latest comment about karlson so telling you here, I sent you the code and such. I can't do much more over KA because my "John" account just got banned and I don't want my latest alt to be banned.

**Comment by Dddatt** [comment]
Ok, your alt is now NoCow if i remember right??

**Comment by Reginald-Gillespie** [comment]
Yeah, though be careful because I don't trust them not to stalk this thread.
